"""Module for calculating the QRISK3 score for individuals in a dataset.

This is adapted from https://github.com/YanLiUK/QRISK3/blob/master/R/QRISK3-2017ver9.R, 
which in turn is based on the original QRISK3-2017 model, which was available at  https://qrisk.org/src.php. 
This model was published under a LGPL license but does not seem to be available any longer (as of March 2026).

This Python implementation has been tested against the R implementation, but NOT against the 
original QRISK3-2017 model, as it is no longer available.

The original QRISK3 model formula including original variable names and model beta coefficients
is under the license of LGPL and copyright to ClinRisk Ltd. The LGPL license is displayed here in full:

Details:
========

Copyright 2017 ClinRisk Ltd.

QRISK3-2017 is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
  
QRISK3-2017 is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.
  
You should have received a copy of the GNU Lesser General Public License
along with QRISK3-2017.  If not, see http://www.gnu.org/licenses/.
  
Additional terms
  
The following disclaimer must be held together with any risk score score generated by this code.  
If the score is displayed, then this disclaimer must be displayed or otherwise be made easily accessible, 
e.g. by a prominent link alongside it. The initial version of this file, to be found at 
http://svn.clinrisk.co.uk/opensource/qrisk2, faithfully implements QRISK3-2017. ClinRisk Ltd. have released this code 
under the GNU Lesser General Public License to enable others to implement the algorithm faithfully. However, the nature 
of the GNU Lesser General Public License is such that we cannot prevent, for example, someone accidentally altering the 
coefficients, getting the inputs wrong, or just poor programming. ClinRisk Ltd. stress, therefore, that it is the 
responsibility of the end user to check that the source that they receive produces the same results as the original 
code found at https://qrisk.org. Inaccurate implementations of risk scores can lead to wrong patients being given the 
wrong treatment.
  
End of additional terms
"""
import numpy as np
import polars as pl


def calculate_qrisk3(data: pl.DataFrame) -> pl.Series:
    """Calculate the QRISK3 score for each individual in the dataset.
    
    This function returns the 10 year risk of cardiovascular disease for each individual in the dataset, 
    as a percentage.

    TODO: Implement statin effect. 
    """
    # Apply age and BMI transformations
    data = data.with_row_index()
    # Split the data in to male and female; apply the appropriate risk calculation to each group,
    # and then combine the results back together in the original order
    male_data = data.filter(pl.col("Sex") == "Male")
    female_data = data.filter(pl.col("Sex") == "Female")

    male_risk_scores = male_data.with_columns(male_risk(male_data))
    female_risk_scores = female_data.with_columns(female_risk(female_data))

    # Combine the results back together in the original order using the row index
    risk_scores = pl.concat([male_risk_scores, female_risk_scores]).sort("index")["risk"]

    return risk_scores

def female_age_bmi_transformation(data: pl.DataFrame) -> pl.DataFrame:
    """Apply the age and BMI transformations to the dataset."""
    return data.with_columns(
        (pl.col("Age") / 10).alias("dage"),
        (pl.col("BMI") / 10).alias("dbmi")
    ).with_columns(
        pl.col("dage").pow(-2).alias("age_1"),
        pl.col("dage").alias("age_2"),
        pl.col("dbmi").pow(-2).alias("bmi_1"),
        (pl.col("dbmi").pow(-2) * pl.col("dbmi").log()).alias("bmi_2")
    )

def male_age_bmi_transformation(data: pl.DataFrame) -> pl.DataFrame:
    """Apply the age and BMI transformations to the dataset."""
    return data.with_columns(
        (pl.col("Age") / 10).alias("dage"),
        (pl.col("BMI") / 10).alias("dbmi")
    ).with_columns(
        pl.col("dage").pow(-1).alias("age_1"),
        pl.col("dage").pow(3).alias("age_2"),
        pl.col("dbmi").pow(-2).alias("bmi_1"),
        (pl.col("dbmi").pow(-2) * pl.col("dbmi").log()).alias("bmi_2")
    )

#pylint: disable=too-many-statements
def female_risk(data: pl.DataFrame) -> pl.Series:
    """Calculate the risk score for females in the dataset."""

    if any(data["Sex"].is_in(["Female"]).not_()):
        raise ValueError("Data contains non-female entries in the Sex column")

    survival_10years = 0.988876402378082

    data = female_age_bmi_transformation(data)

    # Centre continuous variables
    data = data.with_columns(
        (pl.col("age_1") - 0.053274843841791),
        (pl.col("age_2") - 4.332503318786621),
        (pl.col("bmi_1") - 0.154946178197861),
        (pl.col("bmi_2") - 0.144462317228317),
        (pl.col("Cholesterol_HDL_Ratio") - 3.476326465606690),
        (pl.col("Systolic_Blood_Pressure") - 123.130012512207030),
        (pl.col("SD_Systolic_Blood_Pressure") - 9.002537727355957),
        (pl.col("Townsend_Score") - 0.392308831214905)
    )

    a = 0.0
    a += ethnicity_risk(data)
    a += smoking_risk(data)

    # Risk from continuous variables
    a += data['age_1'] * -8.13881092477261880
    a += data['age_2'] * 0.79733376689699098
    a += data['bmi_1'] * 0.29236092275460052
    a += data['bmi_2'] * -4.15133002138376650
    a += data['Cholesterol_HDL_Ratio'] * 0.15338035820802554
    a += data['Systolic_Blood_Pressure'] * 0.013131488407103424
    a += data['SD_Systolic_Blood_Pressure'] * 0.0078894541014586095
    a += data['Townsend_Score'] * 0.077223790588590108

    # Risk from boolean variables
    a += data['Atrial_Fibrillation'] * 1.5923354969269663
    a += data['Atypical_Antipsychotics'] * 0.25237642070115557
    a += data['Corticosteroids'] * 0.59520725304601851
    a += data['Migraine'] * 0.301267260870345
    a += data['Rheumatoid_Arthritis'] * 0.21364803435181942
    a += data['CKD'] * 0.65194569493845833
    a += data['Severe Mental Illness'] * 0.12555308058820178
    a += data['SLE'] * 0.75880938654267693
    a += data['Treated Hypertension'] * 0.50931593683423004
    a += data['Type 1 Diabetes'] * 1.7267977510537347
    a += data['Type 2 Diabetes'] * 1.0688773244615468
    a += data['Family History of CVD'] * 0.45445319020896213

    # Risk from interactions
    a += data['age_1'] * (data['Smoking Status'] == "Ex Smoker") * -4.7057161785851891
    a += data['age_1'] * (data['Smoking Status'] == "Light Smoker") * -2.7430383403573337
    a += data['age_1'] * (data['Smoking Status'] == "Moderate Smoker") * -0.86608088829392182
    a += data['age_1'] * (data['Smoking Status'] == "Heavy Smoker") * 0.90241562369710648
    a += data['age_1'] * data['Atrial_Fibrillation'] * 19.938034889546561
    a += data['age_1'] * data['Corticosteroids'] * -0.98408045235936281
    a += data['age_1'] * data['Migraine'] * 1.7634979587872999
    a += data['age_1'] * data['CKD'] * -3.5874047731694114
    a += data['age_1'] * data['SLE'] * 19.690303738638292
    a += data['age_1'] * data['Treated Hypertension'] * 11.872809733921812
    a += data['age_1'] * data['Type 1 Diabetes'] * -1.2444332714320747
    a += data['age_1'] * data['Type 2 Diabetes'] * 6.8652342000009599
    a += data['age_1'] * data['bmi_1'] * 23.802623412141742
    a += data['age_1'] * data['bmi_2'] * -71.184947692087007
    a += data['age_1'] * data['Family History of CVD'] * 0.99467807940435127
    a += data['age_1'] * data['Systolic_Blood_Pressure'] * 0.034131842338615485
    a += data['age_1'] * data['Townsend_Score'] * -1.0301180802035639
    a += data['age_2'] * (data['Smoking Status'] == "Ex Smoker") * -0.075589244643193026
    a += data['age_2'] * (data['Smoking Status'] == "Light Smoker") * -0.11951192874867074
    a += data['age_2'] * (data['Smoking Status'] == "Moderate Smoker") * -0.10366306397571923
    a += data['age_2'] * (data['Smoking Status'] == "Heavy Smoker") * -0.13991853591718389
    a += data['age_2'] * data['Atrial_Fibrillation'] * -0.076182651011162505
    a += data['age_2'] * data['Corticosteroids'] * -0.12005364946742472
    a += data['age_2'] * data['Migraine'] * -0.065586917898699859
    a += data['age_2'] * data['CKD'] * -0.22688873086442507
    a += data['age_2'] * data['SLE'] * 0.077347949679016273
    a += data['age_2'] * data['Treated Hypertension'] * 0.00096857823588174436
    a += data['age_2'] * data['Type 1 Diabetes'] * -0.28724064624488949
    a += data['age_2'] * data['Type 2 Diabetes'] * -0.097112252590695489
    a += data['age_2'] * data['bmi_1'] * 0.52369958933664429
    a += data['age_2'] * data['bmi_2'] * 0.045744190122323759
    a += data['age_2'] * data['Family History of CVD'] * -0.076885051698423038
    a += data['age_2'] * data['Systolic_Blood_Pressure'] * -0.0015082501423272358
    a += data['age_2'] * data['Townsend_Score'] * -0.031593414674962329

    risk = 100.0 * (1 - (survival_10years**np.exp(a)))

    return pl.Series("risk", risk)

#pylint: disable=too-many-statements
def male_risk(data: pl.DataFrame) -> pl.Series:
    """Calculate the risk score for males in the dataset."""

    if any(data["Sex"].is_in(["Male"]).not_()):
        raise ValueError("Data contains non-male entries in the Sex column")

    survival_10years = 0.977268040180206

    data = male_age_bmi_transformation(data)

    # Centre continuous variables
    data = data.with_columns(
        (pl.col("age_1") - 0.234766781330109),
        (pl.col("age_2") - 77.284080505371094),
        (pl.col("bmi_1") - 0.149176135659218),
        (pl.col("bmi_2") - 0.141913309693336),
        (pl.col("Cholesterol_HDL_Ratio") - 4.300998687744141),
        (pl.col("Systolic_Blood_Pressure") - 128.571578979492190),
        (pl.col("SD_Systolic_Blood_Pressure") - 8.756621360778809),
        (pl.col("Townsend_Score") - 0.526304900646210)
    )

    a = 0.0
    a += ethnicity_risk(data)
    a += smoking_risk(data)

    # Risk from continuous variables
    a += data['age_1'] * -17.839781666005575
    a += data['age_2'] * 0.0022964880605765492
    a += data['bmi_1'] * 2.4562776660536358
    a += data['bmi_2'] * -8.3011122314711354
    a += data['Cholesterol_HDL_Ratio'] * 0.17340196856327111
    a += data['Systolic_Blood_Pressure'] * 0.012910126542553305
    a += data['SD_Systolic_Blood_Pressure'] * 0.010251914291290456
    a += data['Townsend_Score'] * 0.033268201277287295

    # Risk from boolean variables
    a += data['Atrial_Fibrillation'] * 0.8820923692805465700000000
    a += data['Atypical_Antipsychotics'] * 0.1304687985517351300000000
    a += data['Corticosteroids'] * 0.4548539975044554300000000
    a += data['Erectile_Disfunction'] * 0.2225185908670538300000000
    a += data['Migraine'] * 0.2558417807415991300000000
    a += data['Rheumatoid_Arthritis'] * 0.209706580139565670000000
    a += data['CKD'] * 0.7185326128827438400000000
    a += data["Severe Mental Illness"] * 0.1213303988204716400000000
    a += data['SLE'] * 0.4401572174457522000000000
    a += data['Treated Hypertension'] * 0.5165987108269547400000000
    a += data['Type 1 Diabetes'] * 1.2343425521675175000000000
    a += data['Type 2 Diabetes'] * 0.8594207143093222100000000
    a += data['Family History of CVD'] * 0.5405546900939015600000000

    # Risk from interactions
    a+= data['age_1'] * (data['Smoking Status'] == "Ex Smoker") * -0.2101113393351634600000000
    a+= data['age_1'] * (data['Smoking Status'] == "Light Smoker") * 0.7526867644750319100000000
    a+= data['age_1'] * (data['Smoking Status'] == "Moderate Smoker") * 0.9931588755640579100000000
    a+= data['age_1'] * (data['Smoking Status'] == "Heavy Smoker") * 2.1331163414389076000000000
    a+= data['age_1'] * data['Atrial_Fibrillation'] * 3.4896675530623207000000000
    a+= data['age_1'] * data['Corticosteroids'] * 1.1708133653489108000000000
    a+= data['age_1'] * data['Erectile_Disfunction'] * -1.5064009857454310000000000
    a+= data['age_1'] * data['Migraine'] * 2.3491159871402441000000000
    a+= data['age_1'] * data['CKD'] * -0.5065671632722369400000000
    a+= data['age_1']* data['Treated Hypertension'] * 6.5114581098532671000000000
    a+= data['age_1'] * data['Type 1 Diabetes'] * 5.3379864878006531000000000
    a+= data['age_1'] * data['Type 2 Diabetes'] * 3.6461817406221311000000000
    a+= data['age_1'] * data['bmi_1'] * 31.0049529560338860000000000
    a+= data['age_1'] * data['bmi_2'] * -111.2915718439164300000000000
    a+= data['age_1'] * data['Family History of CVD'] * 2.7808628508531887000000000
    a+= data['age_1'] * data['Systolic_Blood_Pressure'] * 0.0188585244698658530000000
    a+= data['age_1'] * data['Townsend_Score'] * -0.1007554870063731000000000
    a+= data['age_2'] * (data['Smoking Status'] == "Ex Smoker") * -0.0004985487027532612100000
    a+= data['age_2'] * (data['Smoking Status'] == "Light Smoker") * -0.0007987563331738541400000
    a+= data['age_2'] * (data['Smoking Status'] == "Moderate Smoker") * -0.0008370618426625129600000
    a+= data['age_2'] * (data['Smoking Status'] == "Heavy Smoker") * -0.0007840031915563728900000
    a+= data['age_2'] * data['Atrial_Fibrillation'] * -0.0003499560834063604900000
    a+= data['age_2'] * data['Corticosteroids'] * -0.0002496045095297166000000
    a+= data['age_2'] * data['Erectile_Disfunction'] * -0.0011058218441227373000000
    a+= data['age_2'] * data['Migraine'] * 0.0001989644604147863100000
    a+= data['age_2'] * data['CKD'] * -0.0018325930166498813000000
    a+= data['age_2']* data['Treated Hypertension'] * 0.0006383805310416501300000
    a+= data['age_2'] * data['Type 1 Diabetes'] * 0.0006409780808752897000000
    a+= data['age_2'] * data['Type 2 Diabetes'] * -0.0002469569558886831500000
    a+= data['age_2'] * data['bmi_1'] * 0.0050380102356322029000000
    a+= data['age_2'] * data['bmi_2'] * -0.0130744830025243190000000
    a+= data['age_2'] * data['Family History of CVD'] * -0.0002479180990739603700000
    a+= data['age_2'] * data['Systolic_Blood_Pressure'] * -0.0000127187419158845700000
    a+= data['age_2'] * data['Townsend_Score'] * -0.0000932996423232728880000

    risk = 100.0 * (1-(survival_10years**np.exp(a)))

    return pl.Series("risk", risk)

def smoking_risk(data: pl.DataFrame) -> pl.Series:
    """Calculate the smoking risk score for each individual in the dataset."""
    # Define the risk score based on smoking status
    risk_female = {
        "Non-Smoker": 0.0000,
        "Ex Smoker": 0.13386833786546262,
        "Light Smoker": 0.56200858012438537,
        "Moderate Smoker": 0.66749593377502547,
        "Heavy Smoker": 0.84948177644830847
    }

    risk_male = {
        "Non-Smoker": 0.0000,
        "Ex Smoker": 0.19128222863388983,
        "Light Smoker": 0.55241588192645552,
        "Moderate Smoker": 0.63835053027506072,
        "Heavy Smoker": 0.78983819881858019
    }

    return pl.select(
        pl.when(
            data["Sex"] == "Male"
        ).then(
            data["Smoking Status"].replace(risk_male)
        ).otherwise(
            data["Smoking Status"].replace(risk_female)
        ).alias("smoking_risk")
    )['smoking_risk'].cast(pl.Float64)

def ethnicity_risk(data: pl.DataFrame) -> pl.Series:
    """Calculate the ethnicity risk score for each individual in the dataset."""
    risk_female = {
        "White": 0.0,
        "Indian": 0.28040314332995425,
        "Pakistani": 0.56298994142075398,
        "Bangladeshi": 0.29590000851116516,
        "Other Asian": 0.072785379877982545,
        "Black Caribbean": -0.17072135508857317,
        "Black African": -0.39371043314874971,
        "Chinese": -0.32632495283530272,
        "Other Ethnic Group": -0.17127056883241784
    }

    risk_male = {
        "White": 0.0,
        "Indian": 0.27719248760308279,
        "Pakistani": 0.47446360714931268,
        "Bangladeshi": 0.52961729919689371,
        "Other Asian": 0.035100159186299017,
        "Black Caribbean": -0.35807899669327919,
        "Black African": -0.40056485232165140,
        "Chinese": -0.41522792889830173,
        "Other Ethnic Group": -0.26321348134749967
    }

    # Check for invalid entries in the Ethnicity column
    assert set(risk_female.keys()) == set(risk_male.keys()), \
    "Risk dictionaries for males and females do not have the same keys"
    valid_keys = set(risk_female.keys())
    if any(data["Ethnicity"].is_in(valid_keys).not_()):
        raise ValueError("Invalid entries found in the Ethnicity column")


    return pl.select(
        pl.when(
            data["Sex"] == "Male"
        ).then(
            data["Ethnicity"].replace(risk_male)
        ).otherwise(
            data["Ethnicity"].replace(risk_female)
        ).alias("ethnicity_risk")
    )['ethnicity_risk'].cast(pl.Float64)
